### ISSUE TITLE
Xcode9 打包失败

### ISSUE THREAD

**Issue by niunaruto** [huangxuan518/HXPackRobot#13]

**Comment by moonclock** [comment]
请上传一下报错信息,如:
Check dependencies
Code Signing Error: Provisioning profile "XC iOS Ad Hoc: com.liqiang365app.musen" is Xcode managed, but signing settings require a manually managed profile.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'

**Comment by niunaruto** [comment]
The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/myMac/Library/Developer/Xcode/DerivedData/myApp-gcilurmquavnardbutkhwerruqti/Build/Intermediates.noindex/ArchiveIntermediates/myApp/IntermediateBuildFilesPath/myApp.build/Release-iphoneos/myApp.build/Script-00CE16ABACD530FEA71510A3.sh
(1 failure)
Now using system ruby.
+ xcodebuild -exportArchive -archivePath /Users/myMac/4.0.0/build/myApp.xcarchive -exportPath /Users/myMac/Desktop/PackRobot/myApp_2017-10-10-17-52-55 -exportOptionsPlist /Users/myMac/Desktop/PackRobot/exportOptionsPlist.plist
error: archive not found at path '/Users/myMac/4.0.0/build/myApp.xcarchive'

**Comment by moonclock** [comment]
初步判断,应该是exportOptionsPlist.plist配置错误,请按教程重新配置.

另: xcode 9 中 exportOptionsPlist.plist 需要增加一个字段,形如

`
<key>provisioningProfiles</key>
	<dict>
		<key>com.xxx.app(app名称)</key>
		<string>app_test(证书描述名称)</string>
	</dict>
` 
github 上稍后几天会更新该 plist

**Comment by niunaruto** [comment]
添加了，不行一样的错误

**Comment by moonclock** [comment]
请上传一下报错信息

**Comment by niunaruto** [comment]
和上边的错误一样

**Comment by moonclock** [comment]
1. PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/myMac/Library/Developer/Xcode/DerivedData/myApp-gcilurmquavnardbutkhwerruqti/Build/Intermediates.noindex/ArchiveIntermediates/myApp/IntermediateBuildFilesPath/myApp.build/Release-iphoneos/myApp.build/Script-00CE16ABACD530FEA71510A3.sh'
尝试执行 pod install 去解决.
2.  xcodebuild -exportArchive -archivePath /Users/myMac/4.0.0/build/myApp.xcarchive -exportPath /Users/myMac/Desktop/PackRobot/myApp_2017-10-10-17-52-55 -exportOptionsPlist /Users/myMac/Desktop/PackRobot/exportOptionsPlist.plist
error: archive not found at path '/Users/myMac/4.0.0/build/myApp.xcarchive'
请确定exportOptionsPlist.plist中,该键值
 <key>method</key>
        <string>ad-hoc</string>

**Comment by Pineapple8662** [comment]
2017-10-11 12:02:26.009 xcodebuild[13439:242356] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fe1091968c0>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
    "Error Domain=IDEProvisioningErrorDomain Code=9 \"\"CWBM_alpha.app\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"CWBM_alpha.app\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the \"provisioningProfiles\" dictionary in your Export Options property list.}"
)}
error: exportArchive: "CWBM_alpha.app" requires a provisioning profile.

Error Domain=IDEProvisioningErrorDomain Code=9 ""CWBM_alpha.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="CWBM_alpha.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

**Comment by Pineapple8662** [comment]
我的也是打不了的

**Comment by moonclock** [comment]
@CoderSimonWong CoderSimonWong 你的是因为 xcode9打包 exportOptionsPlist.plist 需要增加一个provisioningProfiles字段,我已经更新对应文件,等待原作者合并以后,相应配置一下就可以了

**Comment by niunaruto** [comment]
tks ok 了

**Comment by Pineapple8662** [comment]
先谢谢大佬，坐等大佬更新。

**Comment by moonclock** [comment]
@CoderSimonWong 你可以直接在 exportOptionsPlist.plist中添加如下字段:
```objective-c
  <key>provisioningProfiles</key> 
  <dict> <key>com.xxx.app(app名称)</key> <string>app_test(证书描述名称)</string> </dict>
```
