### ISSUE TITLE
项目中两个TAGETS 其中一个是NotificationService 现在打包的时候提示错误了 

### ISSUE THREAD

**Issue by hanxueshi** [huangxuan518/HXPackRobot#16]
The following build commands failed:
	Check dependencies
(1 failure)
/Users/hanxueshi/Desktop/PackRobot/xcodebuild-safe.sh: line 29: rvm: command not found
+ xcodebuild -exportArchive -archivePath /Users/hanxueshi/Desktop/DHB/build/DHBIos.xcarchive -exportPath /Users/hanxueshi/Desktop/PackRobot/DHBIos_2017-11-28-11-25-46 -exportOptionsPlist /Users/hanxueshi/Desktop/PackRobot/exportOptionsPlist.plist
error: archive not found at path '/Users/hanxueshi/Desktop/DHB/build/DHBIos.xcarchive'

**Comment by moonclock** [comment]
额，原作者一直没有合并代码，建议你去#13中去看我的回答

**Comment by hanxueshi** [comment]
我的Xcode是8.3.1版本的   也是在info里面添加这个么字段么

**Comment by moonclock** [comment]
@hanxueshi 额,抱歉,没给你说明白
请查看#13中这个回答的第二条,https://github.com/huangxuan518/HXPackRobot/issues/13#issuecomment-335661095

**Comment by hanxueshi** [comment]
在配置信息中添加   <key>provisioningProfiles</key> 
  <dict> <key>com.xxx.app(app名称)</key> <string>app_test(证书描述名称)</string> </dict>   这个字段是不？

**Comment by moonclock** [comment]
不不，点击那个#13，进去直接就是我的回答

我把答案拷过来了吧。
请确定exportOptionsPlist.plist中,该键值
method
ad-hoc

**Comment by hanxueshi** [comment]
好来  我试一下 3Q

**Comment by hanxueshi** [comment]
还是报之前的错误

**Comment by moonclock** [comment]
建议排查一下, svm 状态,可以参考
https://stackoverflow.com/questions/11677771/rvm-command-not-found-mac-ox
