### ISSUE TITLE
error: archive not found at path '/Users/pajia/Desktop/xxxx/build/shehui.xcarchive

### ISSUE THREAD

**Issue by gonyua** [huangxuan518/HXPackRobot#2]
你好
error: archive not found at path '/Users/pajia/Desktop/xxxx/build/shehui.xcarchive 一直提示没找到 但是工程根目录确定是对的 还有哪儿的问题导致

**Comment by huangxuan518** [comment]
@gongyua  目前我这边好像也有问题，是升级xcode导致的，等我找到解决方案会更新

**Comment by gonyua** [comment]
@huangxuan518 好的 谢了

**Comment by huangxuan518** [comment]
@gongyua  上面那个不是工程目录，应该是你的打包工具所在目录
