### ISSUE TITLE
一直提示这个，怎么办？

### ISSUE THREAD

**Issue by luoxiao** [huangxuan518/HXPackRobot#21]
你好～，一直提示这个，怎么办？

xcodebuild: error: 'PicEditor.xcworkspace' does not exist.

**Comment by moonclock** [comment]
方便的话,请检查一下配置路径如:
project_path    = "~Desktop/PackRobot/PicEditor"               # 项目根目录

project_type中pod工程使用"-workspace",普通工程用 "-project"

**Comment by moonclock** [comment]
额...长期没回复,先把这个 issues 关了吧,有其他问题的朋友,请新建 issues.
@huangxuan518

**Comment by huangxuan518** [comment]
@luoxiao  这个请百度吧，应该不是打包脚本的问题
