### ISSUE TITLE
打包成功之后 发送邮件上传fir失败 

### ISSUE THREAD

**Issue by gonyua** [huangxuan518/HXPackRobot#4]
你好 新的HXPackRobot成功打包 但是发送邮件上传fir失败 帮忙看下什么问题

Exported shehui.xcarchive to: /Users/pajia/Desktop/PackRobot/shehui_2017-08-04-17-37-09
** EXPORT SUCCEEDED **

{"code":201,"message":"_api_key not found","data":[]}send: 'ehlo pajiademac-mini.local\r\n'
reply: '250-smtp.qq.com\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-SIZE 73400320\r\n'
reply: '250-STARTTLS\r\n'
reply: '250-AUTH LOGIN PLAIN\r\n'
reply: '250-AUTH=LOGIN\r\n'
reply: '250-MAILCOMPRESS\r\n'
reply: '250 8BITMIME\r\n'
reply: retcode (250); Msg: smtp.qq.com
PIPELINING
SIZE 73400320
STARTTLS
AUTH LOGIN PLAIN
AUTH=LOGIN
MAILCOMPRESS
8BITMIME
send: 'AUTH PLAIN ADY2MzYzMDA0MkBxcS5jb20AZ3kxOTkzNTE3MA==\r\n'
reply: '535 Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256\r\n'
reply: retcode (535); Msg: Error: ??ʹ????Ȩ???¼???????뿴: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
Traceback (most recent call last):
  File "/Users/pajia/Desktop/PackRobot/pack.py", line 134, in <module>
    main()
  File "/Users/pajia/Desktop/PackRobot/pack.py", line 129, in main
    send_mail()
  File "/Users/pajia/Desktop/PackRobot/pack.py", line 104, in send_mail
    server.login(from_addr, password)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by huangxuan518** [comment]
@gongyua  _api_key not found，你看下是不是没填

**Comment by gonyua** [comment]
_api_key not found 中 api_key没看到有填的地方  只有fir_api_token
fir_api_token = "a8f722c82b4bc159a357316839b82XXX" 之前检查过确定都填了

**Comment by moonclock** [comment]
1. (关键)  _api_key not found是蒲公英的上传报错,说明上传方式选择判断失误.

   能否提供程序头部上传配置信息,为了避免泄露隐私,请像这样提供(保持XX位数与原位数一致):
  fir_api_token = "a8f722c82b4bc159a357316839b82XXX" 

     ps.
     程序的上传方式判断依赖于fir_api_token的值,如果使用 fir.im请保持此值为全局.

2.  (配置错误) qq邮箱发送邮件需要授权码(非邮箱密码)，可参考报错信息中的链接获取，然后将获取的授权码赋值给邮箱密码.
