### ISSUE TITLE
我的是企业开发者账号 能打包吗

### ISSUE THREAD

**Issue by PengJiang520** [huangxuan518/HXPackRobot#6]

**Comment by PengJiang520** [comment]
Last login: Wed Aug 23 16:43:25 on ttys000
jiangpengdeMacBook-Pro:~ jiangpeng$ python ~/Desktop/PackRobot/pack.py
** PACKROBOT START **
=== CLEAN TARGET  OF PROJECT app WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

Create product structure
/bin/mkdir -p /Users/jiangpeng/Desktop/项目/天宝/app/build/Release-iphoneos/天宝.app

Clean.Remove clean build/SharedPrecompiledHeaders/App-cbtxwcxkxscrglfqxsutqvxztkny/App.pch.pch
    builtin-rm -rf /Users/jiangpeng/Desktop/项目/天宝/app/build/SharedPrecompiledHeaders/App-cbtxwcxkxscrglfqxsutqvxztkny/App.pch.pch

Clean.Remove clean build/Release-iphoneos/天宝.app.dSYM
    builtin-rm -rf /Users/jiangpeng/Desktop/项目/天宝/app/build/Release-iphoneos/天宝.app.dSYM

Clean.Remove clean build/SharedPrecompiledHeaders/App-goegmuapseglneewodddxlvpfput/App.pch.pch
    builtin-rm -rf /Users/jiangpeng/Desktop/项目/天宝/app/build/SharedPrecompiledHeaders/App-goegmuapseglneewodddxlvpfput/App.pch.pch

Clean.Remove clean build/Release-iphoneos/天宝.app
    builtin-rm -rf /Users/jiangpeng/Desktop/项目/天宝/app/build/Release-iphoneos/天宝.app

Clean.Remove clean build/app.build/Release-iphoneos/T宝.build
    builtin-rm -rf /Users/jiangpeng/Desktop/项目/天宝/app/build/app.build/Release-iphoneos/T宝.build

** CLEAN SUCCEEDED **

mkdir: build: File exists
User defaults from command line:
    IDEArchivePathOverride = /Users/jiangpeng/Desktop/项目/天宝/app/build/app

Build settings from command line:
    CODE_SIGN_IDENTITY = iPhone Developer: long li (D9N39VMFW3)
    PROVISIONING_PROFILE = d1a1e2c2-95ab-471a-a8c4-10431ee2ddfe.mobileprovision

xcodebuild: error: Unknown build action 'app-xcworkspace'.
Now using system ruby.
+ xcodebuild -exportArchive -archivePath $'/Users/jiangpeng/Desktop/项?\233?/天?\235/app/build/app.xcarchive' -exportPath /Users/jiangpeng/Desktop/PackRobot/app_2017-08-23-18-22-35 -exportOptionsPlist /Users/jiangpeng/Desktop/PackRobot/exportOptionsPlist.plist
error: archive not found at path '/Users/jiangpeng/Desktop/项目/天宝/app/build/app.xcarchive'
** EXPORT FAILED **

没有找到ipa文件
Traceback (most recent call last):
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 134, in <module>
    main()
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 129, in main
    send_mail()
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 102, in send_mail
    server = smtplib.SMTP(smtp_server, 25)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by PengJiang520** [comment]
会报错

**Comment by PengJiang520** [comment]
如果有时间的话 请留下联系方式 请教下大神

**Comment by huangxuan518** [comment]
@PengJiang520  770493410
