### ISSUE TITLE
是证书选错了吗

### ISSUE THREAD

**Issue by PengJiang520** [huangxuan518/HXPackRobot#9]
Step failed: <IDEDistributionSigningAssetsStep: 0x7fc9605f5000>: Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team Daily Express Co.,Ltd. were found." UserInfo={NSLocalizedDescription=No valid iOS Distribution signing identities belonging to team Daily Express Co.,Ltd. were found.}
error: exportArchive: No valid iOS Distribution signing identities belonging to team Daily Express Co.,Ltd. were found.

Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team Daily Express Co.,Ltd. were found." UserInfo={NSLocalizedDescription=No valid iOS Distribution signing identities belonging to team Daily Express Co.,Ltd. were found.}

**Comment by huangxuan518** [comment]
@PengJiang520  应该是证书问题
